Add lock mechanism to deployment workflow

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -17,7 +17,7 @@ jobs:
         labels: '["no-deployment"]'
       timeout-minutes: 5
     outputs:
-      deploy: "${{ ! steps.check_deployment.outputs.result }}"
+      deploy: "${{ ! fromJson(steps.check_deployment.outputs.result) }}"
 
   pre_commit_ci:
     uses: MorpheusBot/Morpheus-bot/.github/workflows/lint.yml@master
@@ -26,7 +26,7 @@ jobs:
     runs-on: ubuntu-latest
     environment: Production
     needs: [pre_commit_ci, check_deployment]
-    if: github.ref == 'refs/heads/main' && needs.check_deployment.outputs.deploy == 'true'
+    if: github.ref == 'refs/heads/master' && needs.check_deployment.outputs.deploy == 'true'
     permissions:
       contents: read
       packages: write
@@ -39,6 +39,28 @@ jobs:
           username: ${{ secrets.PRODUCTION_USERNAME }}
           port: 22
           script: |
+            echo "================== Lock Mutex =================="
+            LOCK="/tmp/deployment.lock"
+
+            remove_lock()
+            {
+                rm -f "$LOCK"
+            }
+
+            acquire_failed()
+            {
+                echo "Failed to acquire lock, perphaps a stale deployment is running requiring manual fix?"
+                exit 1
+            }
+
+            # !IMPORTANT: For this to work, the remote server has to have `procmail` installed.
+            # Try to lock 5 times with a 60s sleep time between retries
+            # Remove any lock older than 10min (600s) and then wait 30s
+            lockfile -60 -r 5 -l 600 -s 30 "$LOCK" || acquire_failed
+
+            # Remove lock on exit
+            trap remove_lock EXIT
+
             echo "================== Pull Changes =================="
             cd Morpheus
             git pull
